version: '3.8'

services:
  db:
    image: postgres:15
    container_name: couplesdash-db
    restart: always
    environment:
      POSTGRES_DB: couplesdash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: couplesdash:latest
    container_name: couplesdash-app
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/couplesdash
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  pgdata:
